### PR TITLE
Update Portainer to v 2.5.1

### PR DESCRIPTION
**Pull request by unlucio**
Updating Portainer to the current version.

# Proposed Changes

updating from v 1.24.0 to v 2.5.1

## Related Issues

> ([Github link][autolink-references] to related issues or pull requests)

[autolink-references]: https://help.github.com/articles/autolinked-references-and-urls/

### CODE REVIEW

**Comment by sinclairpaul** [comment]
Can you detail the testing that was performed for the upgrade?

**Comment by unlucio** [comment]
I was already using 2.5.1 via `portainer/portainer-ce` from docker hub on another machine.
I decided to move it on the HA host for convenience, and I noticed it was an ancient version.
 
Since the `Dockerfile` only does hass-io ceremonial stuff other than untarring the tar-ball, I thought to bump up the tar's version for "contemporarity".

Other than that I don't write portainer, so not sure what testing I should to besides what everybody using it is already "doing" 😆

**Comment by sinclairpaul** [comment]
There are major changes between 1.x and 2.x for Portainer, particularly around some of the flags used on startup and features they relate to.

Please at least test the functionality locally before submitting a PR.

**Comment by unlucio** [comment]
no idea how 🤷‍♂️

cheers

**Pull request closed without merging**
